### ISSUE TITLE
AttributeError when parsing yaml file with merge keys

### ISSUE THREAD

**Issue by jackemuk** [andrasmaroy/pconf#24]
## Expected Behavior
No AttributeError when loading valid yaml file containing merge keys

## Actual Behavior
An AttributeError: 'list' object has no attribute 'items' is raised when iterating over self.content in __clear_empty_values

## Steps to Reproduce the Problem
1. 
1. Sample file
-----begin yaml file -----
- &CENTER { x: 1, y: 2 }
- &LEFT { x: 0, y: 2 }
- &BIG { r: 10 }
- &SMALL { r: 1 }
-
  << : *CENTER
  r: 10
  label: center/big
-----end yaml file -----
2. Test code

#!/usr/bin/env python3
from pconf import Pconf
import json
Pconf.file('test.yaml', encoding='yaml')
config = Pconf.get()
print(json.dumps(config, sort_keys=True, indent=4))

## Specifications

  - Version: pconf 1.6.1
  - Python: 3.6.8

**Comment by andrasmaroy** [comment]
Sorry for the late reply, I'll look into this next week, thanks for reporting!

**Comment by andrasmaroy** [comment]
@jackemuk frankly the above YAML doesn't make sense in the context of pconf, it is simply a list of maps, while a map (however deep) is expected, what would be the expected output for this?

In my testing merge keys work without any issues (see example below), though I'll fix the issue with parsing lists as reported above.

Example:
```yaml
default: &DEFAULT
  URL: website.com
  mode: production  
  site_name: Website
  some_setting: h2i8yiuhef
  some_other_setting: 3600

development:
  <<: *DEFAULT
  URL: website.local
  mode: dev

test:
  <<: *DEFAULT
  URL: test.website.qa
  mode: test
```
Output:
```json
{
    "default": {
        "URL": "website.com",
        "mode": "production",
        "site_name": "Website",
        "some_setting": "h2i8yiuhef",
        "some_other_setting": 3600
    },
    "development": {
        "URL": "website.local",
        "mode": "dev",
        "site_name": "Website",
        "some_setting": "h2i8yiuhef",
        "some_other_setting": 3600
    },
    "test": {
        "URL": "test.website.qa",
        "mode": "test",
        "site_name": "Website",
        "some_setting": "h2i8yiuhef",
        "some_other_setting": 3600
    }
}
```
